string info_type                                # Type / Name of information.

vda5050_msgs/InfoReference[] info_references    # Array of references.

string info_description                         # Info description.

string info_level                               # Enum {DEBUG, INFO} DEBUG: used for debugging, INFO: used for visualization.

# Enum for info_level
string DEBUG=DEBUG
string INFO=INFO
