float64 speed_min         # [m/s] Minimal controlled continuous speed of the AGV

float64 speed_max         # [m/s] Maximum speed of the AGV

float64 acceleration_max  # [m/s²] Maximum acceleration with maximum load

float64 deceleration_max  # [m/s²] Maximum deceleration with maximum load

float64 height_min        # [m] Minimum height of AGV

float64 height_max        # [m] Maximum height of AGV

float64 width             # [m] Width of AGV

float64 length            # [m] Length of AGV