vda5050_msgs/OptionalParameter[] optional_parameters    # List of supported and/or required optional parameters. 
                                                        # Optional parameters, that are not listed here, are assumed to be not supported by the AGV. 

vda5050_msgs/AgvAction[] agv_actions                    # List of all actions with parameters supported by this AGV. 
                                                        # This includes standard actions specified in VDA5050 and manufacturerspecific actions. 