float32 min_order_interval      # [s], Minimum interval sending order messages to the AGV. 

float32 min_state_interval      # [s], Minimum interval for sending statemessages. 

float32 default_state_interval  # [s], Default interval for sending statemessages, if not defined, the default value from the main document is used. 

float32 visualization_interval  # [s], Default interval for sending messages on visualization topic. 