string zone_id                      # ID of the zone

string zone_type                    # Type of the zone

string name                         # Name of the zone
 
string description                  # Description of the zone

string map_id                       # ID of the map that this zone belongs to.

ZoneParameter[] zone_parameters     # Parameters of the zone

ZonePolygonPoint[] polygon          # List of points that form the polygon of the zone
